### ISSUE TITLE
建议：开放字头编码规则

### ISSUE THREAD

**Issue by tsunhua** [shuowenjiezi/shuowen#3]
我使用简单爬虫的方式（没有进行任何数据存储），做了一个在 Mac 上的 Alfred Workflow 以便可以进行快捷查询汉字的字源，可以同时在三个站点（包括贵站）查询一个汉字的字源。
地址为：https://github.com/LinLshare/AlfredHanziSourceWorkflow
但有时会觉得稍稍慢了点，如果站长不介意的话，我请求开放字头编码规则，便利于他人基于数据源二次开发，传播汉字文化。

**Comment by tsunhua** [comment]
还有本仓库没有使用任何开源协议，这不利于仓库的持续发展，建议加上并补充数据的使用方式，以便开发者共同开发和使用《说文解字》这个宝库。

**Comment by shuowenjiezi** [comment]
首先，感谢您的建议，就像我在仓库说明中解释的，我之所以把 shuowen.org 的数据放到 GitHub，就是希望大家一起完善数据，感兴趣的朋友也可以直接使用，当时没有考虑过开源协议。根据您的建议，我比较之后选择使用  Apache 的开源协议，再次感谢！

关于字头编码，不知您是否指的是 data 目录下面文件名以及字头之间的对应关系，比如  [101.json](https://github.com/shuowenjiezi/shuowen/blob/master/data/101.json)  对应的字头是 "璑"，如果是的话，这之间并没有什么特殊的规则，而是完全按照《说文解字》原文的顺序编号的。
